@hostname=http://localhost:3000

###
POST {{hostname}}/algorithm/submit-code HTTP/1.1
Content-Type: application/json

{
	"compilerId": 62,
	"problemId": 0,
	"code": "class Solution { public int[] twoSum(int[] nums, int target) { int[] sol = {0,2}; return sol; } }"
}

### Get all compiler supported by CQI
GET {{hostname}}/compilers?name=ja HTTP/1.1
Content-Type: application/json


### Get compiler by id
GET {{hostname}}/compilers/0 HTTP/1.1



